Wolox/redux-recompose

package.json, src/index.js
* Introduces some fixes:
-  Declared babel-presents libraries for release use
-  Bug fixing with some var names
=> Fixes for release deployment

src/effects/onToggle/index.js, src/effects/onToggle/test.js
Implemented onToggle effect and it's corresponding tests
=> Introducing onToggle effect

package.json, src/index.js
=> Ontoggle export

README.md, src/middlewares/docs.md
Some documentation added for the   `middlewares` section and the  `fetchMiddleware` function.
=> Middleware docs

README.md, src/injections/withSuccess/docs.md
-Added the doc for withSuccess injector.
=> withSuccess injector docs

README.md, package.json, src/effects/onAppend/docs.md, src/effects/onAppend/index.js, src/effects/onAppend/test.js, src/index.js
Add `onAppend` effect. It appends an element to an array.
Also, updated the `README.md` with the linter rules of vscode. We used to use `*` and `-` for the list items. It replace it all with `-`, among other things.
=> onAppend effect

README.md, package.json, src/effects/onConcatenate/docs.md, src/effects/onConcatenate/index.js, src/effects/onConcatenate/test.js
New `onConcatenate` effect! Like `onAppend`, but all the elements of the arrays end up on the save level.
=> onConcatenate effect

src/effects/onAppend/README.md, src/effects/onConcatenate/README.md
Fix two small documentation errors from my previous PRs :stuck_out_tongue:
=> Fix documentation errors

README.md, src/effects/onSpreadValue/README.md, src/effects/onSpreadValue/index.js
Fixed the `onSpreadValue` effect and formatted the documentation.
=> Fix onSpreadValue effect

README.md, src/injections/withFailure/README.md
Created documentation for the withFailure injector
Trello card : https://trello.com/c/GLT020M6/40-injectors-docs
=> [Injectors docs ] withFailure docs

README.md, src/injections/withFailure/README.md, src/injections/withPostFailure/README.md
Added `withPostFailure`  injector docs
*Trello card:*  https://trello.com/c/GLT020M6/40-injectors-docs
=> [Injector docs] withPostFailure injector docs

README.md, src/injections/withPostSuccess/README.md
Added withPostSuccess documentation both in the main `Readme.md` and the in the `withPostSuccess` injection folder
=> [Injector Docs] Post success docs

.circleci/config.yml, circle.yml
Update circleci to 2.0.
I tried to make the `config.yml` as short as I could.
=> Update circleci to 2.0

src/completers/completeReducer/test.js, src/completers/completeState/index.js, src/completers/completeState/test.js, src/completers/completeTypes/test.js, src/creators/createReducer/index.js, src/creators/createReducer/test.js, src/creators/createTypes/index.js, src/creators/createTypes/test.js, src/utils/typeUtils.js
- Rewrite text errors
- Add new validation for `createType`
=> Test error messages

src/completers/completeReducer/README.md, src/completers/completeState/README.md, src/completers/completeTypes/README.md, src/creators/createReducer/README.md, src/creators/createThunkAction/README.md, src/creators/createTypes/README.md, src/effects/onAppend/README.md, src/effects/onConcatenate/README.md, src/effects/onDelete/README.md, src/effects/onDeleteByIndex/README.md, src/effects/onFailure/README.md, src/effects/onLoaded/README.md, src/effects/onLoading/README.md, src/effects/onReadValue/README.md, src/effects/onSetValue/README.md, src/effects/onSpreadValue/README.md, src/effects/onSuccess/README.md, src/effects/onToggle/README.md, src/injections/withFailure/README.md, src/injections/withPostFailure/README.md, src/injections/withPostSuccess/README.md, src/injections/withSuccess/README.md, src/middlewares/README.md
* Specify code blocks language in completers, creators, effects, injections and middlewares READMEs
=> Specify language in code blocks

.circleci/config.yml, README.md, package.json
In this Pull Request, we will be adding a badge of the code coverage of this library. In order to do this, we have integrated with `CodeCov`(https://codecov.io/)  which provides us with useful tools of coverage reports.
Also we modified the config file of `CircleCI` in order to submit our reports to `CodeCov`, adding the command that submit our reports and also adding to the test command to add coverage.
Finally we add the badge to the `README.md` that `CodeCov` provides us.
Also I want to thank  the special collaboration of @carlosbollero
=> Code coverage

package.json, src/injections/withPreFetch/README.md, src/injections/withPreFetch/index.js, src/injections/withPreFetch/test.js
- Restore `withPreFetch` injection
=> Restore withPreFetch

README.md, src/effects/onCycle/README.md, src/effects/onCycle/index.js, src/effects/onCycle/test.js, src/index.js
Finished the already created onCycle effect.
You can cycle an array as many positions as you indicated. If step params is null, cycle one position.
=> On cycle effect

src/index.js
=> Export onConcatenate effect

README.md, src/effects/onReplace/README.md, src/effects/onReplace/index.js, src/effects/onReplace/test.js, src/index.js
This effect allows modifying an element of an array. Receive a function that tells how to find the element (s) or receives the element's index.
If you pass a function, change all the elements that meet the condition.
https://trello.com/c/Rlq5MFs9/44-onreplace
=> On replace effect

src/index.js
=> Fix onCycle export

.gitignore, package-lock.json, package.json
- Add babel-runtime as peer dependency
- Add package-lock.json
https://trello.com/c/gPtZQFKY
https://trello.com/c/rY18k92R
=> Add babel-runtime as peer dependency, add package-lock.json
